### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by Sighyu** [RealBoppr/InstanceJoiner#3]
NOT WORKING IN OPEN BETA!!!!!!!!!

**Comment by ghost** [comment]
Write kernel level C++ EAC bypass driver to fix, then open source it so they patch again

**Comment by Sighyu** [comment]
> Write kernel level C++ EAC bypass driver to fix, then open source it so they patch again

yes do this boppr we need this mod

**Comment by ghost** [comment]
Honestly a work of modern art, I can't loose this, I only just got it back

**Comment by RealBoppr** [comment]
![StupidKeafy](https://user-images.githubusercontent.com/34575606/181053074-6bea6329-3af7-4fd5-afdd-97eeb5ebb219.png)

**Comment by RealBoppr** [comment]
Yeah, I won't be working on this or any other VRChat mods anymore. Can't be fucked to bypass EAC and probably will just move to ChilloutVR

**Comment by Sighyu** [comment]
Your invalid
